### ISSUE TITLE
Media query does not correspond to cd breakpoints

### ISSUE THREAD

**Issue by left23** [UN-OCHA/common_design#65]
https://github.com/UN-OCHA/common_design/blob/0ab0a1ddfae997cbfe6a3b5dff16f72d7018a81b/components/cd-filters/cd-filters.js#L6

**Comment by rupl** [comment]
so, this might be a bit too much for the situation, but on previous projects where I had lots of breakpoints at specific widths, sometimes we gave them all names and had an element act as glue between CSS and JS. It went like this:

```scss
$breakpoint-1: 454px;
$breakpoint-2: 660px;
$breakpoint-2: 790px;

// Now define labels based on Sass vars.
//
// Note: does not have to be <body>. it just has to be on every page guaranteed.
body {
  &::after { content: 'default'; }
  @media (min-width: $breakpoint-1) {
    &::after { content: 'small'; }
  }
  @media (min-width: $breakpoint-2) {
    &::after { content: 'medium'; }
  }
  @media (min-width: $breakpoint-3) {
    &::after { content: 'large'; }
  }
}
```

Ok so now there will be a pseudo-element and as the window changes size, the element will contain a set of labels.

```js
var currentBreakpoint = window.getComputedStyle(document.querySelector('body'), ':after').content;
```

That way, you never have to declare numbers in JS. You still have to keep labels in sync, but let's pretend the "small" gets moved by 23px later on.. as long as the label didn't change then the JS will automatically use the exact number defined in CSS.
